---
- name: Install Elixir
  yum:
    name: "{{ item }}"
    state: latest
  become: yes
  become_user: root
  with_items: [ "elixir", "inotify-tools" ]
  when: ansible_os_family == 'RedHat'
- name: Install Elixir
  apt:
    name: "{{ item }}"
    state: latest
  become: yes
  become_user: root
  with_items: [ "elixir", "esl-erlang", "inotify-tools" ]
  when: ansible_distribution == 'Ubuntu'
