---
- name: get rustup.sh
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: 0755
- name: install rust
  shell: |
    sh /tmp/rustup.sh -y --no-modify-path
  become: true
  become_user: "{{ user }}"
- name: set restup default
  shell: |
    {{ user_home }}/.cargo/bin/rustup default stable
- name: set component add rust-src
  shell: |
    {{ user_home }}/.cargo/bin/rustup component add rust-src
- name: install rust tools
  shell: |
    {{ user_home }}/.cargo/bin/cargo install {{ item }}
  args:
    creates: '{{ user_home }}/.cargo/bin/{{ item }}'
  with_items: "{{ rust_packages }}"
