---
- hosts: all
  become: no
  vars:
    - user_home: "/home/{{ user }}"
    - goroot:    "{{ user_home }}/go"
    - gopath:    "{{ user_home }}/dev"
    - go14root:  "{{ user_home }}/go1.4"
  pre_tasks:
    - set_fact:
        user: "{{ ansible_ssh_user }}"
      when: user is not defined
  roles:
    - python3
    - go
    - rust
    - develop
    - nvim
    - jq
    - role: zaxos.docker-ce-ansible-role
      become: true
      become_user: root
  tasks:
    - name: "make dev-user able to use docker"
      become: true
      become_user: root
      user:
        name: "{{ user }}"
        groups: "docker"
        append: yes
