---
- hosts: all
  become: no
  vars:
    - develop_user: "{{ user }}"
    - develop_home: "{{ user_home }}"
    - go_dir: "{{ user_home }}"
    - vim_dir: "{{ user_home }}/local"
    - tmux_dir: "{{ user_home }}/local"
    - tmux_xpane_dir: "{{ user_home }}/local"
    - jq_dir: "{{ user_home }}/local"
    - ctags_dir: "{{ user_home }}/local"
    - develop_set_github_key: yes
  pre_tasks:
    - set_fact:
        user: "{{ ansible_user }}"
      when: user is not defined
    - set_fact:
        user_home: "/home/{{ user }}"
      when: user_home is not defined
  roles:
    # - role: common
      # - role: develop
      # - role: andrewrothstein.bazel
      #   bazel_ver: 0.13.0
      #   bazel_checksums:
      #     '0.13.0':
      #       linux-x86_64: sha256:c90ed6d8478fd543d936702d2eb3ed034f46b2223fac790598db70c161552418
      # - role: rust
      #   become: yes
      #   become_user: "{{ user }}"
      # - role: python3
      #   become: yes
      #   become_user: "{{ user }}"
      ## - role: go
      ### - role: ruby
      ###   become: yes
      ###   become_user: "{{ user }}"
      # - role: ctags
      #   become: yes
      #   become_user: "{{ user }}"
      ### - role: nodejs
      ###   become: yes
      ###   become_user: "{{ user }}"
      # - role: sdkman
      #   become: yes
      #   become_user: "{{ user }}"
      # - role: fzf
      # - role: vim
      #   become: yes
      #   become_user: "{{ user }}"
      # - role: nvim
      #   become: yes
      #   become_user: "{{ user }}"
      # - role: tmux
      #   become: yes
      #   become_user: "{{ user }}"
      # - role: tmux-xpanes
      #   become: yes
      #   become_user: "{{ user }}"
      # - role: jq
      #   become: yes
      #   become_user: "{{ user }}"
    - role: zaxos.docker-ce-ansible-role
      become: true
      become_user: root
      when: ansible_system != "Darwin"
    - role: cimon-io.asdf
      asdf_user: "{{ user }}"
      asdf_plugins:
        - name: "erlang"
          versions: ["19.3", "20.2"]
          global: "20.2"
        - name: "elixir"
          versions: ["1.6.4"]
          global: "1.6.4"
      when: ansible_system != "Darwin"
  tasks:
    - name: "make dev-user able to use docker"
      become: true
      become_user: root
      user:
        name: "{{ ansible_ssh_user }}"
        groups: "docker"
        append: yes
      when: ansible_system != "Darwin"
