---
- name: restart_sshd
  become: yes
  block:
  - service:
      name: ssh
      state: restarted
    async: 1
    poll: 0
  - name: Wait for the reboot to complete if there was a change.
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
