---
- include: main-Darwin.yml
  when: ansible_system == "Darwin"
- include: main-RedHat.yml
  when: ansible_os_family == 'RedHat'
- include: main-Debian.yml
  when: ansible_os_family == 'Debian'
- name: setup sshconfig
  template:
    src: ssh-config
    dest: "{{ user_home }}/.ssh/config"
    mode: 0644
    backup: yes
- name: setup id_rsa.github
  copy:
    src: develop/id_rsa.github
    dest: "{{ user_home }}/.ssh/id_rsa.github"
    mode: 0600
    owner: "{{ user }}"
    backup: yes
- name: dotfiles をインストールする
  git:
    repo: https://github.com/masu-mi/dotfiles.git
    dest: "{{ user_home }}/dotfiles"
    update: yes
    recursive: yes
    version: master
- name: backup exist .*rc
  shell: |
    if [ -f {{ user_home }}/{{ item }} ]; then
      mv {{ user_home }}/{{ item }} {{ user_home }}/{{ item }}.bak
    fi
  with_items:
    [ .bashrc, .bash_profile, .zshrc ]
# home~以下にdir,linkを作る(本来は dotfilesのMakefileで実行する)
- name: makedirs
  file: path={{ user_home }}/{{ item }} state=directory
  with_items: [
    ".bashrcs",
    "works",
    "local/bin",
    "local/lib",
    "local/doc",
    ".backup/vim",
    ".config",
    ]
- name: dotfiles のlinkを作成する
  file: src={{ user_home }}/dotfiles/{{ item }} path={{ user_home }}/{{ item }} state=link
  with_items: [ .ackrc, .bashrc, .bash_profile, .gitconfig, .inputrc, .screenrc, .tmux.conf, .vim, .zshrc, .sqliterc ]
- name: for nvim
  file: src={{ user_home }}/dotfiles/.vim path={{ user_home }}/.config/nvim state=link
- name: for vim
  file: src={{ user_home }}/dotfiles/.vim/init.vim path={{ user_home }}/.vimrc state=link
- name: .bash_tokens を作成する(サービストークン用)
  file: path={{ user_home }}/.bash_tokens state=touch
