---
- name: Install apt libraries(Debian)
  become: yes
  become_user: root
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    [
      ntp, ntp-doc, ntpdate,
      build-essential, m4, gcc-6-base,
      curl, git, mercurial, wget,
      llvm, lldb,
      telnet, tmux, lsof, tcpdump,
      openjdk-8-jdk,
      vim, ruby, texinfo,
      libtool, libtool-bin, autoconf, automake, g++, pkg-config, unzip, cmake,
      libcurl4-openssl-dev, libexpat-dev, libncurses-dev, zlib1g-dev, libbz2-dev,
      fakeroot, build-essential, gcc-arm-linux-gnueabihf,
      libncurses5, libncurses5-dev, libelf-dev, binutils-dev, devscripts,
      u-boot-tools,
    ]
