---
- shell: pip3 install --upgrade pip
  register: result
  changed_when: '"Requirement already up-to-date" not in result.stdout'
- shell: pip3 install --upgrade setuptools
  register: result
  changed_when: '"Requirement already up-to-date" not in result.stdout'
- name: install pkgs with pip3
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items: "{{ pip3_pkgs }}"
