---
- include: main-Darwin.yml
  when: ansible_system == "Darwin"
- include: main-CentOS.yml
  when: ansible_os_family == 'RedHat'
- include: main-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
- include: install-pip-packages.yml
  when: ansible_distribution != 'Darwin'
- include: install-pip-packages.yml
  become: yes
  become_user: root
  when: ansible_distribution == 'Darwin'
