---
- block:
    - name: install dependency(Redhat)
      yum: name={{ item }} state=present
      with_items: [
        "libevent", "libevent-devel",
        "utf8proc", "utf8proc-devel",
      ]
      when: ansible_os_family == 'RedHat'
    - name: install dependency(Ubuntu)
      apt: name={{ item }} update_cache=yes
      with_items: "{{ tmux_dependent_apt_pkgs[ansible_distribution_major_version] }}"
      when: ansible_distribution == 'Ubuntu'
  become: yes
  become_user: root
  when: ansible_system != 'Darwin'
- name: fetch tmux source
  get_url:
    url: https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz
    dest: "/tmp/tmux-{{ tmux_version }}.tar.gz"
- name: install tmux
  shell: |
    tar xzf ./tmux-{{ tmux_version }}.tar.gz
    cd ./tmux-{{ tmux_version }}
    ./configure \
      --prefix={{ tmux_dir }} \
      --enable-utf8proc
    make
    make install
  args:
    chdir: /tmp/
    creates: "{{ tmux_dir }}/bin/tmux"
  when: ansible_system != 'Darwin'
