---
- include: install-pip-neovim.yml
  when: ansible_system != "Darwin"
- include: install-pip-neovim.yml
  become: yes
  become_user: root
  when: ansible_system == "Darwin"
- name: get nvim source
  git: repo=https://github.com/neovim/neovim.git version=v0.3.1 dest=/tmp/neovim.git
- name: install nvim for Darwin
  homebrew:
    name: nvim
    state: present
  when: ansible_system == "Darwin"
- name: install nvim for Linux
  shell: |
    make distclean
    make CMAKE_EXTRA_FLAGS="-DCMAKE_INSTALL_PREFIX={{ user_home }}/local"
    make install
  args:
    chdir: /tmp/neovim.git
    creates: '{{ user_home }}/local/bin/nvim'
  when: not ansible_system == "Darwin"
