---
- name: install dependencies
  yum: name={{ item }} state=present
  with_items:
    [ openssl-devel, readline-devel ]
  become: yes
  become_user: root
  when: ansible_os_family == 'RedHat'
- name: install dependencies
  apt: name={{ item }} state=present
  with_items:
    [ libssl-dev, libreadline-dev ]
  become: yes
  become_user: root
  when: ansible_distribution == 'Ubuntu'
- name: fetch rbenv
  git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "{{ user_home }}/.rbenv"
    version: "{{ rbenv_version }}"
- name: build rbenv
  shell: |
    src/configure && make -C src
  args:
    creates: "{{ user_home }}/.rbenv/bin/rbenv"
- set_fact:
    rbenv_root: "{{ user_home }}/.rbenv"
- file:
    path: "{{ rbenv_root }}/plugins"
    state: directory
- name: install ruby-build
  git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "{{ rbenv_root }}/plugins/ruby-build"
    version: "{{ ruby_build_version }}"
- name: install rubies
  shell: |
    {{ user_home }}/.rbenv/bin/rbenv init > /dev/null 2>&1
    {{ user_home }}/.rbenv/bin/rbenv install -s {{ item }}
  with_items: "{{ ruby_versions }}"
